repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: spotless-check
        name: Check code format with Spotless
        entry: mvn spotless:check
        language: system
        pass_filenames: false

      - id: maven-test
        name: Run Maven Tests
        entry: mvn test
        language: system
        pass_filenames: false
